### ISSUE TITLE
Incorporating changes from Word

### ISSUE THREAD

**Issue by Pakillo** [noamross/rmd-rant#2]
Thanks for this @noamross. Very useful

I have a question for Strategy 3: how do you revise and incorporate the changes made in Word? Do you convert Word to Markdown with pandoc then Diff and Merge? Is there a good tool for the last step? I was using SourceDiffMerge but it's a bit cumbersome (I particularly miss the ability to accept/reject by word, not by line). 
Now I'm tending to revise and accept changes in Word, then pasting the text manually back into the Rmd...

As you have thought a lot about this and tried many things, interested to know your approach.

Thanks!

**Comment by noamross** [comment]
I generally incorporate by hand or copy-paste, after merging multiple Word edits in Word. Some folks on the original issue thread follow the approach you describe, though.

**Comment by Pakillo** [comment]
Excellent, thanks!
